package jp.co.cyberagent.valor.jdbc;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import jp.co.cyberagent.valor.spi.ValorConnection;
import jp.co.cyberagent.valor.spi.exception.ValorException;
import jp.co.cyberagent.valor.spi.plan.TupleScanner;
import jp.co.cyberagent.valor.spi.plan.model.RelationScan;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public abstract class ValorJdbcStatementBase implements Statement {

  static Logger LOG = LoggerFactory.getLogger(ValorJdbcStatementBase.class);

  protected ValorJdbcConnection connection;

  protected ResultSet resultSet;

  public ValorJdbcStatementBase(ValorJdbcConnection connection) {
    this.connection = connection;
  }

  @SuppressWarnings("unchecked")
  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return (T) this;
    }
    throw new SQLException(new IllegalArgumentException(iface.getCanonicalName()
        + " in not a warrper of this class"));
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return iface.isInstance(this);
  }

  @Override
  public void close() throws SQLException {
  }

  protected ResultSet doExecuteSelect(RelationScan query) throws SQLException {
    ValorConnection vc = connection.getValorConnection();
    try {
      TupleScanner scanner = vc.compile(query);
      return new ValorResultSet(scanner);
    } catch (ValorException | IOException e) {
      throw new SQLException(e);
    }
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("executeQuery() is not implemented");
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("executeUpdate() is not implemented");
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("executeUpdate() is not implemented");
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("executeUpdate() is not implemented");
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("executeUpdate() is not implemented");
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("execute() is not implemented");
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("execute() is not implemented");
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("execute() is not implemented");
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("execute() is not implemented");
  }

  @Override
  public int[] executeBatch() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("executeBatch() is not implemented");
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getMaxFieldSize");
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setMaxFieldSize");
  }

  @Override
  public int getMaxRows() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getMaxRows");
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setMaxRows");
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setEscapeProcessing");
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getQueryTimeout");
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setQueryTimeout");
  }

  @Override
  public void cancel() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("cancel");
  }

  // CHECKSTYLE:OFF
  @Override
  public SQLWarning getWarnings() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getWarnings");
  }
  // CHECKSTYLE:ON

  @Override
  public void clearWarnings() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("clearWarnings");
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setCursorName");
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    return this.resultSet;
  }

  @Override
  public int getUpdateCount() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getUpdateCount");
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getMoreResults");
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getMoreResults");
  }

  @Override
  public int getFetchDirection() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getFetchDirection");
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setFetchDirection");
  }

  @Override
  public int getFetchSize() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getFetchSize");
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setFetchSize");
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getResultSetConcurrency");
  }

  @Override
  public int getResultSetType() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getResultSetType");
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("addBatch");
  }

  @Override
  public void clearBatch() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("clearBatch");
  }

  @Override
  public Connection getConnection() throws SQLException {
    return connection;
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getGeneratedKeys");
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getResultSetHoldability");
  }

  @Override
  public boolean isClosed() throws SQLException {
    return this.connection.isClosed();
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return false;
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setPoolable() is not implemented");
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("closeOnCompletion() is not implemented");
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("isCloseOnCompletion() is not implemented");
  }


}
