package jp.co.cyberagent.valor.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import jp.co.cyberagent.valor.ql.parse.Parser;
import jp.co.cyberagent.valor.sdk.ValorConnectionFactory;
import jp.co.cyberagent.valor.spi.ValorConnection;
import jp.co.cyberagent.valor.spi.ValorContext;
import jp.co.cyberagent.valor.spi.plan.model.LogicalPlanNode;
import jp.co.cyberagent.valor.spi.plan.model.ParameterizedStatement;

public class ValorJdbcConnection implements Connection {

  private final ValorConnection conn;
  private final Parser parser;

  public ValorJdbcConnection(ValorContext context) {
    this.conn = ValorConnectionFactory.create(context);
    this.parser = new Parser(conn);
  }

  public ValorConnection getValorConnection() {
    return conn;
  }

  public LogicalPlanNode parse(String query) {
    return parser.parseStatement(query);
  }

  @Override
  public Statement createStatement() throws SQLException {
    return new ValorJdbcStatement(this);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency)
      throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createStatement() is not implemented");
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency,
                                   int resultSetHoldability) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createStatement() is not implemented");
  }

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    ParameterizedStatement query = (ParameterizedStatement) parse(sql);
    return new ValorPreparedStatement(query, this);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareStatement() is not implemented");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
                                            int resultSetHoldability) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareStatement() is not implemented");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareStatement() is not implemented");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareStatement() is not implemented");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareStatement() is not implemented");
  }

  @Override
  public Clob createClob() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createClob() is not implemented");
  }

  @Override
  public Blob createBlob() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createBlob() is not implemented");
  }

  @Override
  public NClob createNClob() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createNClob() is not implemented");
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createSQLXML() is not implemented");
  }

  @Override
  public boolean isValid(int timeout) throws SQLException {
    // TODO check connection
    return true;
  }

  @Override
  public void setClientInfo(String name, String value) throws SQLClientInfoException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setClientInfo() is not implemented");
  }

  @Override
  public void setClientInfo(Properties properties) throws SQLClientInfoException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setClientInfo() is not implemented");
  }

  @Override
  public String getClientInfo(String name) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getClientInfo() is not implemented");
  }

  @Override
  public Properties getClientInfo() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getClientInfo() is not implemented");
  }

  @Override
  public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createArrayOf() is not implemented");
  }

  @Override
  public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("createStruct() is not implemented");
  }

  @Override
  public void setSchema(String schema) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setSchema() is not implemented");
  }

  @Override
  public String getSchema() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getSchema() is not implemented");
  }

  @Override
  public void abort(Executor executor) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("abort() is not implemented");
  }

  @Override
  public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setNetworkTimeout() is not implemented");
  }

  @Override
  public int getNetworkTimeout() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getNetworkTimeout() is not implemented");
  }

  @Override
  public CallableStatement prepareCall(String sql) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareCall() is not implemented");
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareCall() is not implemented");
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
                                       int resultSetHoldability) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("prepareCall() is not implemented");
  }

  @Override
  public String nativeSQL(String sql) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("nativeSQL() is not implemented");
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    return true;
  }

  @Override
  public void setAutoCommit(boolean autoCommit) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setAutoCommit() is not implemented");
  }

  @Override
  public void commit() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("commit() is not implemented");
  }

  @Override
  public void rollback() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("rollback() is not implemented");
  }

  @Override
  public void rollback(Savepoint savepoint) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("rollback() is not implemented");
  }

  @Override
  public void close() throws SQLException {

  }

  @Override
  public boolean isClosed() throws SQLException {
    return false;
  }

  @Override
  public DatabaseMetaData getMetaData() throws SQLException {
    return new ValorJdbcMetaData();
  }

  @Override
  public void setReadOnly(boolean readOnly) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setReadOnly() is not implemented");
  }

  @Override
  public boolean isReadOnly() throws SQLException {
    return false;
  }

  @Override
  public void setCatalog(String catalog) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setCatalog() is not implemented");
  }

  @Override
  public String getCatalog() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getCatalog() is not implemented");
  }

  @Override
  public void setTransactionIsolation(int level) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setTransactionIsolation() is not implemented");
  }

  @Override
  public int getTransactionIsolation() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getTransactionIsolation() is not implemented");
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getWarnings() is not implemented");
  }

  @Override
  public void clearWarnings() throws SQLException {
    // TODO Auto-generated method stub
  }

  @Override
  public Map<String, Class<?>> getTypeMap() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getTypeMap() is not implemented");
  }

  @Override
  public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setTypeMap() is not implemented");
  }

  @Override
  public void setHoldability(int holdability) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setHoldability() is not implemented");
  }

  @Override
  public int getHoldability() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("getHoldability() is not implemented");
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setSavepoint() is not implemented");
  }

  @Override
  public Savepoint setSavepoint(String name) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("setSavepoint() is not implemented");
  }

  @Override
  public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("releaseSavepoint() is not implemented");
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("unwrap() is not implemented");
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("isWrapperFor() is not implemented");
  }
}
